codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: nearest
  range: "70...90"

  status:
    project:
      default:
        target: 85%
        threshold: 5%
    patch:
      default:
        target: 85%
        threshold: 5%
    changes: no

  ignore:
    - "./AEPUserProfile/Tests/.*"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
